// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmizec0Zu0FdlV91YEAKmEycJts004X4c',
    appId: '1:507759935433:web:77ac780472bc32d272b218',
    messagingSenderId: '507759935433',
    projectId: 'appointnow-2bdba',
    authDomain: 'appointnow-2bdba.firebaseapp.com',
    storageBucket: 'appointnow-2bdba.firebasestorage.app',
    measurementId: 'G-N7HFGT48WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABjtOKRdqqAZx4g6pett9SGQkgNe-_MsE',
    appId: '1:507759935433:android:053fba5f2ec4c3a972b218',
    messagingSenderId: '507759935433',
    projectId: 'appointnow-2bdba',
    storageBucket: 'appointnow-2bdba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa2sr4ta6sFuppoeC9sSlsaXluokY-M-E',
    appId: '1:507759935433:ios:60991e1b9e8fcef172b218',
    messagingSenderId: '507759935433',
    projectId: 'appointnow-2bdba',
    storageBucket: 'appointnow-2bdba.firebasestorage.app',
    iosBundleId: 'com.example.appointnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa2sr4ta6sFuppoeC9sSlsaXluokY-M-E',
    appId: '1:507759935433:ios:60991e1b9e8fcef172b218',
    messagingSenderId: '507759935433',
    projectId: 'appointnow-2bdba',
    storageBucket: 'appointnow-2bdba.firebasestorage.app',
    iosBundleId: 'com.example.appointnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmizec0Zu0FdlV91YEAKmEycJts004X4c',
    appId: '1:507759935433:web:2c0fe935e0a03a8572b218',
    messagingSenderId: '507759935433',
    projectId: 'appointnow-2bdba',
    authDomain: 'appointnow-2bdba.firebaseapp.com',
    storageBucket: 'appointnow-2bdba.firebasestorage.app',
    measurementId: 'G-6N0ZKC6D08',
  );
}
